notARepository: "quit"
os:
  editPreset: "nvim"
gui:
  nerdFontsVersion: "3"
  filterMode: "fuzzy"
  mouseEvents: true
  sidePanelWidth: 0.25
git:
  paging:
    colorArg: "always"
    pager: "delta --paging=never"
